config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root "posts#index"
  resources :posts
  
  resources :categories do
    resources :posts
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :posts
	
	extend FriendlyId
	friendly_id :name, use: :slugged
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_and_belongs_to_many :categories
	belongs_to :user
	is_impressionable :counter_cache => true, :column_name => :view_count

	acts_as_taggable_on :tags

	extend FriendlyId
	friendly_id :title, use: :slugged

	scope :featured, -> { where(:featured => true) }

	scope :recent, -> { order(created_at: :desc) }
	scope :hot,    -> { order(view_count: :desc) }
	scope :longest, -> { order(duration: :desc) }


	def self.sort_by(sort_param)
	  case sort_param
	  when 'recent'
	    recent
	  when 'hot'
	    hot
	  when 'longest'
	    longest
	  else
	    recent
	  end
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'carrierwave/orm/activerecord'

  def authorize_admin
    redirect_to root_path, alert: 'Access Denied' unless current_user && current_user.admin?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@category = Category.friendly.find(params[:id])
    @posts = @category.posts.all.paginate(page: params[:page], per_page: 40)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize_admin, only: :new
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.all.sort_by(params[:order]).paginate(page: params[:page], per_page: 40)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    impressionist(@post)
    @recent_posts = Post.where.not(id: @post.id).order('created_at desc').limit(6)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def authorized_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this link" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :image, :affiliate, :description, :duration, :tag_list, :video, :featured, :category, :featuredone, :featuredtwo, :categorytwo, :categorythree, :categoryfour, :category_ids => [])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    if User.any?
      redirect_to root_path, alert: 'Only one user allowed!' and return
    end
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/categories/show.html.erb
<div class="category-banner">
  <div class="jumbotron <%= @category.name %>">
      <div class="container">
        <h1><%= @category.name %></h1>
      </div>
  </div>
</div>

<div class="container" id="container">

  <% @posts.each do |post| %>

    <div class="widget" >

    <%= link_to post do %>
      
      <div class="image" style="background-image:url('<%= post.image %>')">
      </div>

      <div class="caption">
        <div class="tags">
          <% post.categories.each do |category| %>
              <%= link_to category_path(category) do %>
                <div class="tag <%= category.name %>">#<%= category.name %></div>
              <% end %>
          <% end %>
        </div>
        <h4><%= post.title %></h4>
        <p class="meta"><%= post.impressionist_count(:filter=>:all) %> views &middot; <a href="<%= post.url %>"><%= post.affiliate %></a> </p>
      </div> 

    <% end %>
    </div>
  <% end %>

  <div class="pagination">
    <div class="digg_pagination">
      <%= will_paginate @posts, :container => false, :inner_window => 2, :previous_label => 'Prev', :next_label => 'Next →' %>
    </div>
  </div>


</div>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pz </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= metamagic %>


  <script src="https://jwpsrv.com/library/5+TPBsz_EeSBUhJtO5t17w.js"></script>
  <script src="//use.typekit.net/kah0vyw.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="https://fontastic.s3.amazonaws.com/X9uxQeFcKw4C2ETyztppGG/icons.css" rel="stylesheet">

  
  
</head>
<body>



<nav class="navbar yamm navbar-default navbar-fixed-top">
 <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-brand">
         <a href="/">
            <div class="logo"></div>
         </a>
     </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li>
          <a href="#" class="discover">
            <i class="icon-hashtag icon"></i>Discover <span class="caret"></span>
          </a>
          <ul>
              <div class="container">
                <div class="row">
                  <div class="col-md-2">
                    <a href="/categories/amateur">Amateur</a>
                    <a href="/categories/anal">Anal</a>
                    <a href="/categories/arab">Arab</a>
                    <a href="/categories/asian">Asian</a>
                    <a href="/categories/babe">Babe</a>
                    <a href="/categories/babysitter">Babysitter</a>
                    <a href="/categories/big-ass">Big Ass</a>
                    <a href="/categories/big-dick">Big Dick</a>
                    <a href="/categories/big-tits">Big Tits</a>
                    <a href="/categories/blonde">Blonde</a>
                  </div>
                  <div class="col-md-2">
                    <a href="/categories/blowjob">Blowjob</a>
                    <a href="/categories/bondage">Bondage</a>
                    <a href="/categories/british">British</a>
                    <a href="/categories/brunette">Brunette</a>
                    <a href="/categories/bukkake">Bukkake</a>
                    <a href="/categories/cartoon">Cartoon</a>
                    <a href="/categories/casting">Casting</a>
                    <a href="/categories/celebrity">Celebrity</a>
                    <a href="/categories/college">College</a>
                    <a href="/categories/compilation">Compilation</a>
                  </div>
                  <div class="col-md-2">
                    <a href="/categories/creampie">Creampie</a>
                    <a href="/categories/cumshots">Cumshots</a>
                    <a href="/categories/double-penetration">Double Penetration</a>
                    <a href="/categories/ebony">Ebony</a>
                    <a href="/categories/euro">Euro</a>
                    <a href="/categories/feet">Feet</a>
                    <a href="/categories/fetish">Fetish</a>
                    <a href="/categories/fisting">Fisting</a>
                    <a href="/categories/for-women">For Women</a>
                    <a href="/categories/french">French</a>                   
                  </div>
                  <div class="col-md-2">
                    <a href="/categories/gangbang">Gangbang</a>
                    <a href="/categories/german">German</a>
                    <a href="/categories/handjob">Handjob</a>
                    <a href="/categories/hardcore">Hardcore</a>
                    <a href="/categories/indian">Indian</a>
                    <a href="/categories/interracial">Interracial</a>
                    <a href="/categories/italian">Italian</a>
                    <a href="/categories/japanese">Japanese</a>
                    <a href="/categories/korean">Korean</a>
                    <a href="/categories/latina">Latina</a>  
                  </div>
                  <div class="col-md-2">
                    <a href="/categories/lesbian">Lesbian</a>
                    <a href="/categories/massage">Massage</a>
                    <a href="/categories/masturbation">Masturbation</a>
                    <a href="/categories/mature">Mature</a>
                    <a href="/categories/milf">MILF</a>
                    <a href="/categories/orgy">Orgy</a>
                    <a href="/categories/party">Party</a>
                    <a href="/categories/pornstar">Pornstar</a>
                    <a href="/categories/pov">POV</a>
                    <a href="/categories/public">Public</a>  
                  </div>
                  <div class="col-md-2">
                    <a href="/categories/pussy-licking">Pussy Licking</a>
                    <a href="/categories/reality">Reality</a>
                    <a href="/categories/rough-sex">Rough Sex</a>
                    <a href="/categories/school">School</a>
                    <a href="/categories/small-tits">Small Tits</a>
                    <a href="/categories/squirt">Squirt</a>
                    <a href="/categories/teen">Teen</a>
                    <a href="/categories/threesome">Threesome</a>
                    <a href="/categories/toys">Toys</a>
                    <a href="/categories/uniform">Uniform</a>  
                  </div>
                </div>
              </div>
          </ul>
        </li>
        <li><a href="#" class="cams"><i class="icon-record icon"></i>Cams</a></li>
        <li><a href="#" class="hd"><i class="icon-hd icon"></i>Members  <span class="label label-success">PRO</span></a></li>

      </ul>
  
      <ul class="nav navbar-nav navbar-right">
        <li><a><i class="fa fa-search"></i>Search</a></li>
        <% if user_signed_in? %>

          <% if current_user.try(:admin?) %>
            <li><%= link_to 'Submit link', new_post_path %></li>
          <% end %>

        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>



<%= yield %>




<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62586051-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :affiliate %><br>
    <%= f.text_field :affiliate %>
  </div>

  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>

  <%= f.label :category_ids, "Categories" %><br />
  <%= f.collection_select :category_ids, Category.order(:name), :id, :name, {}, {multiple: true} %>

 
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>

  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>

  <div class="field">
    <%= f.label "Is it featured?" %> <br />
    <%= f.check_box :featured %> <br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p><b>Title:</b> <%= @post.title %></p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <div class="jumbotron">
    <div class="container">
      <h1>Free HD Trailers. No Gimmicks. No Bullshit</h1>
      <p>Is the best trailer site you’ve never heard of. </p>
    </div>
  </div>

<div class="container" id="container">

  <% @posts.each do |post| %>


    <div class="widget" >

    <%= link_to post do %>
      
      <div class="image" style="background-image:url('<%= post.image %>')">
      </div>

    <div class="tags">
      <% post.categories.each do |category| %>
          <%= link_to category_path(category) do %>
            <div class="tag <%= category.name %>"><%= category.name %></div>
          <% end %>
      <% end %>
    </div>

    <% end %>
    </div>
  <% end %>

  <div class="pagination">
    <div class="digg_pagination">
      <%= will_paginate @posts, :container => false, :inner_window => 2, :previous_label => 'Prev', :next_label => 'Next →' %>
    </div>
  </div>


</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
    <div class="container">

      <div class="row">
        
        <div class="col-md-9">
            <div id="myElement">Loading the player...</div>
        </div>

        <div class="col-md-3">
            
        </div>

      </div>

      <div class="row">
        <div class="col-md-9 info">
          <div class="container-fluid sidebar">
            <div class="row">
              <div class="col-md-12">
                <h1><%= @post.title %></h1>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p class="meta"><%= @post.impressionist_count(:filter=>:all) %> views &middot; <a href="<%= @post.url %>"><%= @post.affiliate %></a></p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p class="description"><%= @post.description %></p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <a href="<%= @post.url %>" class="view-more">Watch full on <%= @post.affiliate %> &rarr;</a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="tags">
                  <% @post.categories.each do |category| %>
                      <%= link_to category_path(category) do %>
                        <div class="tag <%= category.name %>"><%= category.name %></div>
                      <% end %>
                  <% end %>
                </div>
              </div>
            </div>
  
        </div>     
      </div>
      </div>
    </div>
  </div>





        <script type="text/javascript">
            jwplayer("myElement").setup({
                file: "<%= @post.video %>",
                image: "<%= @post.image %>",
                stretching: "fill",
                width: "100%",
                aspectratio: "16:9"
            });
        </script>

    </div>






<% if @post.user == current_user %>
  <td><%= link_to 'Edit', edit_post_path(@post) %></td>
  <td><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/posts/tagged.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Image</th>
      <th>Affiliate</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.image %></td>
        <td><%= post.affiliate %></td>
        <td><%= post.duration %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>